### ISSUE TITLE
Assume installation in /opt/pynab

### ISSUE THREAD

**Issue by f-laurens** [pguyot/nabblockly#11]
For compatibility with Pynab (PR# https://github.com/nabaztag2018/pynab/pull/334)
`nabblockly.service` should at some point be updated to assume installation in `/opt/pynab`:
```
WorkingDirectory=/opt/pynab/nabblockly
ExecStart=/opt/pynab/nabblockly/_build/default/rel/nabblockly/bin/nabblockly foreground
```

**Comment by pguyot** [comment]
It's pynab's responsiblity.
The installation in a home dir makes perfectly sense, installing in /opt requires sudo privileges.

https://github.com/nabaztag2018/pynab/blob/master/install.sh#L376

**Comment by f-laurens** [comment]
Fine.
But it means we must be careful very to keep this "historical" handling of `/home/pi`:
`-e "s|/opt/pynab|${root_dir}|g" -e "s|/home/pi/pynab|${root_dir}|g"`
in Pynab's `install.sh`

**Comment by pguyot** [comment]
See https://github.com/nabaztag2018/pynab/issues/122
nabblockly should be one among many
