### ISSUE TITLE
Lesson 5 frustration

### ISSUE THREAD

**Issue by f-laurens** [pguyot/nabblockly#6]
Lesson 5, when provided with a correct 'script':
![lesson5-1](https://user-images.githubusercontent.com/33164641/117139985-206e9e80-adad-11eb-8012-71fb64a5376d.png)
yields following result:
![lesson5-2](https://user-images.githubusercontent.com/33164641/117140049-367c5f00-adad-11eb-8e77-3cdf142a3f9d.png)

**Comment by f-laurens** [comment]
Thanks!

**Comment by f-laurens** [comment]
Hmmm..... Maybe I'm confused here, but it still fails with the fix....

**Comment by pguyot** [comment]
Did you reload the page to make sure it's not in the cache? You can also check the JS source code.

**Comment by f-laurens** [comment]
Ooops... It was indeed apparently a **damn cache** issue.
Thanks for the fix.
